# Generated by Django 4.2.7 on 2026-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100, unique=True)),
                ("team_size", models.IntegerField()),
                (
                    "payment_proof",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("utr_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "registrations_team",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=20)),
                ("college_code", models.CharField(max_length=20)),
                ("college_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=254)),
                ("tshirt_size", models.CharField(max_length=5)),
            ],
            options={
                "db_table": "registrations_teammember",
                "managed": False,
            },
        ),
    ]
